ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: false
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map

    # IMU topic
    imu0: "/imu/data"
    imu0_config: [
      false, false, false,   # x, y, z
      true,  true,  true,    # roll, pitch, yaw (orientation)
      false, false, false,   # x_vel, y_vel, z_vel (linear velocity)
      true,  true,  true     # roll_vel, pitch_vel, yaw_vel (angular velocity)
    ]
    imu0_differential: false
    imu0_queue_size: 5

    # Remove gravity from IMU data
    imu0_remove_gravitational_acceleration: true

    # GPS topic
    gps0: "/gps/fix"
    gps0_config: [
      true,  true,  false,   # x, y, z positions
      false, false, false,   # roll, pitch, yaw
      false, false, false,   # linear velocity
      false, false, false    # angular velocity
    ]
    gps0_queue_size: 5

    # ...additional advanced params...
